"""add boost column in instrument table

Revision ID: 097beb9229c4
Revises: 356e9e993ffe
Create Date: 2019-06-23 10:15:27.261605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097beb9229c4'
down_revision = '356e9e993ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('boost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument', 'boost')
    # ### end Alembic commands ###
