"""add drawdown column in position_setting table

Revision ID: 356e9e993ffe
Revises: 70b77369e517
Create Date: 2019-06-17 11:53:10.468936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356e9e993ffe'
down_revision = '70b77369e517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_setting', sa.Column('drawdown', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_setting', 'drawdown')
    # ### end Alembic commands ###
