"""add boost_last_update column on instrument table

Revision ID: 4927ba6f1247
Revises: 097beb9229c4
Create Date: 2019-06-23 10:49:19.358812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4927ba6f1247'
down_revision = '097beb9229c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('boost_last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument', 'boost_last_update')
    # ### end Alembic commands ###
