"""position-setting add column: profit_val, return_pct

Revision ID: 70b77369e517
Revises: cfa74a9dc39b
Create Date: 2019-06-07 16:31:20.003993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b77369e517'
down_revision = 'cfa74a9dc39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_setting', sa.Column('profit_val', sa.Float(), nullable=True))
    op.add_column('position_setting', sa.Column('return_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_setting', 'return_pct')
    op.drop_column('position_setting', 'profit_val')
    # ### end Alembic commands ###
