"""transfer, portfolio tables

Revision ID: 7ba7adff4768
Revises: a3ec472719b4
Create Date: 2019-06-02 16:49:20.065936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba7adff4768'
down_revision = 'a3ec472719b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('stocks_value', sa.Float(), nullable=False),
    sa.Column('coins_value', sa.Float(), nullable=False),
    sa.Column('cash_value', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['previous_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
