"""instrument, tag tables

Revision ID: a3ec472719b4
Revises: 
Create Date: 2019-06-02 13:16:08.019735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ec472719b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('robinhood_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('sector', sa.String(length=40), nullable=True),
    sa.Column('industry', sa.String(length=40), nullable=True),
    sa.Column('market_cap', sa.Integer(), nullable=True),
    sa.Column('low_52_weeks', sa.Float(), nullable=True),
    sa.Column('high_52_weeks', sa.Float(), nullable=True),
    sa.Column('average_volume', sa.Integer(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('ceo', sa.String(length=40), nullable=True),
    sa.Column('headquarters_city', sa.String(length=40), nullable=True),
    sa.Column('headquarters_state', sa.String(length=40), nullable=True),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol'),
    sa.UniqueConstraint('robinhood_id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrument.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('instrument')
    # ### end Alembic commands ###
