"""some columns on portfolio, position tables are nullable now

Revision ID: c13a3b31807a
Revises: 60f2f5a23050
Create Date: 2019-06-03 10:20:01.869532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13a3b31807a'
down_revision = '60f2f5a23050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('portfolio', 'today_return_pct',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('portfolio', 'total_return_pct',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('position', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('position', 'today_return_pct',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('position', 'total_return_pct',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('position', 'total_return_pct',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('position', 'today_return_pct',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('position', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('portfolio', 'total_return_pct',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('portfolio', 'today_return_pct',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('portfolio', 'last_update',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
