"""position-setting table

Revision ID: cfa74a9dc39b
Revises: d8d4da5e4d76
Create Date: 2019-06-07 09:50:44.333819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa74a9dc39b'
down_revision = 'd8d4da5e4d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('proportion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['instrument.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_setting')
    # ### end Alembic commands ###
